language: node_js
node_js:
  - '10'
cache:
  directories:
    - node_modules
before_install:
  - npm prune
before_script:
  - git config --global user.email "build-ci@axa.fr"
  - git config --global user.name "Build-CI"
branches:
  only:
    - master
install:
  - npm install
script:
  - npm run build
deploy:
  provider: page  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  keep-history: true
