language: node_js
node_js:
  - '10'
branches:
  only:
    - master
install:
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  keep-history: true
  local-dir: dist
  repo: samuel-gomez-axa/samuel-gomez-axa.github.io
